/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/portfoliobackground.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Light" position={[6.63, 8.35, -2.61]} rotation={[-1.84, 0.6, 1.93]} scale={[88.31, 339.47, 232.82]} />
        <group name="dummyobject" position={[-0.92, 0.53, 1.09]} rotation={[-0.38, 1.49, -2.74]} scale={[1.18, 0.04, 8.42]} />
        <PerspectiveCamera name="Camera" makeDefault={false} far={100} near={0.1} fov={35.86} position={[8.17, 3.63, 4.02]} rotation={[-0.81, 1.13, 0.76]} scale={[3.33, 2.76, 4.88]} />
        <mesh name="stack2" geometry={nodes.stack2.geometry} material={materials.Opaque} position={[0, 0.63, -0.11]} rotation={[-0.02, 1.49, -3.13]} scale={2.89} />
        <mesh name="stack1-2" geometry={nodes['stack1-2'].geometry} material={materials.Opaque} position={[0, 1.33, -0.12]} rotation={[0, 1.5, 3.13]} scale={2.89} />
        <mesh name="stack1-1" geometry={nodes['stack1-1'].geometry} material={materials.Transparent} position={[0, 1.57, -0.12]} rotation={[0.23, 1.49, 2.91]} scale={2.89} />
        <mesh name="Corner" geometry={nodes.Corner.geometry} material={materials.Transparent} position={[0.66, 2.26, 0.28]} rotation={[-0.38, 1.49, -2.74]} scale={2.89} />
        <mesh name="float2" geometry={nodes.float2.geometry} material={materials.Transparent} position={[0.45, 1.81, -1]} rotation={[-0.38, 1.49, -2.74]} scale={2.89} />
        <mesh name="Smallside" geometry={nodes.Smallside.geometry} material={materials.Transparent} position={[0.78, 2.39, -0.44]} rotation={[0.06, 1.39, 3.12]} scale={2.89} />
        <mesh name="leftfloat" geometry={nodes.leftfloat.geometry} material={materials.Transparent} position={[0, 2.1, 0.43]} rotation={[-0.38, 1.49, -2.74]} scale={2.89} />
        <mesh name="cover1" geometry={nodes.cover1.geometry} material={materials.Transparent} position={[0, 2.37, -0.06]} rotation={[-0.4, 1.49, -2.74]} scale={2.89} />
        <mesh name="cover2" geometry={nodes.cover2.geometry} material={materials.Transparent} position={[0, 1.99, -0.11]} rotation={[-0.5, 1.47, 0.49]} scale={2.89} />
        <mesh name="float3" geometry={nodes.float3.geometry} material={materials.Transparent} position={[-0.26, 1.79, -0.67]} rotation={[0.04, -0.09, 0]} scale={2.89} />
        <mesh name="curverside" geometry={nodes.curverside.geometry} material={materials.Transparent} position={[-0.22, 1.81, 0]} rotation={[-0.5, 1.47, 0.49]} scale={2.89} />
        <mesh name="gridplane" geometry={nodes.gridplane.geometry} material={materials.Gridplane} position={[-26.94, 0.01, -8.64]} rotation={[0, -0.07, 0]} scale={[37.55, 1, 32.55]} />
      </group>
    </group>
  )
}

useGLTF.preload('/portfoliobackground.gltf')
