/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props: any) {
  const group = useRef();
  const { scene, animations } = useGLTF("/portfoliobackground.gltf", true);

  const { actions, mixer } = useAnimations(animations, group);
  useEffect(() => {
    for (const [key, _value] of Object.entries(actions)) {
      actions[key]?.play();
    }
  }, [mixer]);

  return <primitive ref={group} object={scene} dispose={null} />;
}

useGLTF.preload("/portfoliobackground.gltf");
